<a href="https://colab.research.google.com/github/jesusrevilla/2022Q2GO-Bootcamp/blob/main/Miner%C3%ADa_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minería de Datos

## Primer parcial

### Introducción

#### Conceptos

#### Ciencia de Datos

IPython Magic Commands

In [ ]:
# Sirve para evaluar el desempño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

66.2 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# Con doble porcentaje podemo evaluar el desempeño
# en cuanto tiempo de más de una línea de código
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)


90.2 µs ± 25.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [ ]:
!ls

'1. Planeacion academia MD prim2025.pdf'   sample_data


In [ ]:
!pwd

/content


In [ ]:
!echo "printing from the shell"

printing from the shell


In [ ]:
contents = !ls

In [ ]:
print(contents)

["'1. Planeacion academia MD prim2025.pdf'   sample_data"]


In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
type(directory)

IPython.utils.text.SList

In [ ]:
message = "hello from Python"

In [ ]:
!echo {message}

hello from Python


In [ ]:
%cd /content/

/content


In [ ]:
%ls

'1. Planeacion academia MD prim2025.pdf'   sample_data/


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '6b60292b8627',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [ ]:
# Importa numpy y renombralo como np
import numpy as np

In [ ]:
# Arreglo lineal de enteros

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
# Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
# Cuando el argumento de np.array es una iteración anidada
# genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch

In [1]:
import numpy as np

In [2]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [5]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.random.random((3, 3))

array([[0.56862967, 0.23751592, 0.45846116],
       [0.82577895, 0.54215049, 0.59077261],
       [0.6726727 , 0.50873403, 0.18434749]])

In [10]:
np.random.normal(0, 1, 5)

array([-1.39431041,  0.71417469, -1.98738703, -0.19261897,  0.20914468])

In [14]:
np.random.randint(0, 14, (3, 3))

array([[10,  3,  8],
       [ 4,  8, 12],
       [ 3,  5,  3]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.empty(3)

array([1., 1., 1.])

The Basics of NumPy Arrays

In [17]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [18]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [19]:
print("dtype:", x3.dtype)

dtype: int64


In [20]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [21]:
x1

array([5, 0, 3, 3, 7, 9])

In [22]:
x1[0]

np.int64(5)

In [23]:
x1[3]

np.int64(3)

In [24]:
x1[-1]

np.int64(9)

In [25]:
x1[-2]

np.int64(7)

In [26]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
x2[0, 2]

np.int64(2)

In [29]:
x2[-1, -1] = 2
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 2]])

#### Análisis Estadístico Básico con NumPy

Media (Mean)

In [30]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [31]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [32]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [33]:
mediana = np.median(data)
mediana

np.float64(3.0)

Varianza y Desviación Estándar

In [34]:
varianza = np.var(data)
desviacion = np.std(data)
print(varianza)
print(desviacion)

2.0
1.4142135623730951


Generación de Datos Aleatorios

In [35]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [36]:
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]
