<a href="https://colab.research.google.com/github/jesusrevilla/2022Q2GO-Bootcamp/blob/main/Miner%C3%ADa_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minería de Datos

## Primer parcial

### Introducción

#### Conceptos

#### Ciencia de Datos

IPython Magic Commands

In [1]:
# Sirve para evaluar el desempño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

66.2 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [2]:
# Con doble porcentaje podemo evaluar el desempeño
# en cuanto tiempo de más de una línea de código
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)


90.2 µs ± 25.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [4]:
!ls

'1. Planeacion academia MD prim2025.pdf'   sample_data


In [5]:
!pwd

/content


In [6]:
!echo "printing from the shell"

printing from the shell


In [7]:
contents = !ls

In [8]:
print(contents)

["'1. Planeacion academia MD prim2025.pdf'   sample_data"]


In [9]:
directory = !pwd

In [10]:
print(directory)

['/content']


In [11]:
type(directory)

IPython.utils.text.SList

In [12]:
message = "hello from Python"

In [13]:
!echo {message}

hello from Python


In [16]:
%cd /content/

/content


In [17]:
%ls

'1. Planeacion academia MD prim2025.pdf'   sample_data/


In [18]:
%cd sample_data/

/content/sample_data


In [19]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [20]:
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [21]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '6b60292b8627',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [22]:
# Importa numpy y renombralo como np
import numpy as np

In [23]:
# Arreglo lineal de enteros

In [24]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [27]:
# Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [28]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [29]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [30]:
# Cuando el argumento de np.array es una iteración anidada
# genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])